apiVersion: v1
kind: Secret
metadata:
  name: tekton-hub-api
  namespace: openshift-pipelines
type: Opaque
stringData:
  GH_CLIENT_ID: 'ce93aa391b39048e4146'
  GH_CLIENT_SECRET: '88bd43e803e3e588e76eaeabf6ba70ff8ed63bb5'
  GHE_URL: ''
  GL_CLIENT_ID: ''
  GL_CLIENT_SECRET: ''
  GLE_URL: ''
  BB_CLIENT_ID: ''
  BB_CLIENT_SECRET: ''
  JWT_SIGNING_KEY: 'test'
  ACCESS_JWT_EXPIRES_IN: '5m'
  REFRESH_JWT_EXPIRES_IN: '5m'
  AUTH_BASE_URL: ''
